#!/bin/sh

if [ -z "$TMUX_LAYOUT" ]; then
    layout=$(tmux list-windows -F "#{window_layout} #{window_active}" | awk '/ 1$/ {print $1}')
    tmux split-window -bh env TMUX_LAYOUT=$layout $0 "$@"
else
    cppman "$@"
    tmux kill-pane \; select-layout $TMUX_LAYOUT
fi
