#!/bin/bash

battery_info=`upower -i /org/freedesktop/UPower/devices/battery_BAT0`
is_charging=`echo "$battery_info" | awk 'NR==12 {print $2}'`
time_remain=`echo "$battery_info" | awk 'NR==20 {print $4}'`
time_unit=`echo "$battery_info" | awk 'NR==20 {print substr($5,0,1)}'`
percentage=`echo "$battery_info" | awk 'NR==21 {print substr($2,0,length($2)-1)}' | xargs printf "%.0f"`

#$is_charging
display_charge_status() {
	if [ $is_charging = "charging" ]; then
		echo "▲ "
	elif [ $is_charging = "discharging" ]; then
		echo "▼ "
	fi
}

#$percentage
set_color() {
	if [ $percentage -le 10 ]; then
		echo "colour196" #red
	elif [ $percentage -le 20 ]; then
		echo "colour208" #orange
	elif [ $percentage -le 30 ]; then
		echo "colour226" #yellow
	elif [ $percentage -lt 50 ]; then
		echo "colour20" #blue
	else
		echo "default" #green
	fi
}

#$time_remain, $time_unit 
display_time() {
	if [ $time_unit = "h" ]; then
		echo `printf "%.1f" $time_remain`"h"
	elif [ $time_unit = "m" ]; then
		echo `printf "%.0f" $time_remain`"m"
	fi
}

data="[Batt:"`display_charge_status`${percentage}"% "`display_time`"]"
data="#[bg="`set_color`"]"${data}"#[default]"

echo -e $data
