#!/bin/bash

battery_info=`upower -i /org/freedesktop/UPower/devices/battery_BAT0`
is_charging=`echo "$battery_info" | grep 'state:' | awk '{print $2}'`
time_remain=`echo "$battery_info" | grep 'time to' | awk '{print $4}'`
time_unit=`echo "$battery_info" | grep 'time to' | awk '{print substr($5,0,1)}'`
percentage=`echo "$battery_info" | grep 'percentage:' | awk '{print substr($2,0,length($2)-1)}' | xargs printf "%.0f"`
if [ $percentage = 100 ]; then
	time_remain="0";
	time_unit="m";
fi

#$is_charging
is_charging_icon() {
        if [ $is_charging = "charging" ]; then
                echo "▲ "
        elif [ $is_charging = "discharging" ]; then
                echo "▼ "
	elif [ $is_charging = "fully-charged" ]; then
		echo "● "
        fi
}

#$percentage
colour_code() {
	if [ $percentage -le 10 ]; then
		echo "colour196" #red
	elif [ $percentage -le 20 ]; then
		echo "colour208" #orange
	elif [ $percentage -lt 30 ]; then
		echo "colour178" #yellow
	elif [ $percentage -lt 50 ]; then
		echo "colour26" #blue
	else
		echo "colour112" #green
	fi
}

#$time_remain, $time_unit 
display_time() {
	if [ $time_unit = "h" ]; then
		echo `printf "%.1f" $time_remain`"h"
	elif [ $time_unit = "m" ]; then
		echo `printf "%.0f" $time_remain`"m"
	else
		echo "?m"
	fi
}

ret="[Batt:"`is_charging_icon`${percentage}"% "`display_time`"]"
ret="#[fg="`colour_code`"]"${ret}"#[fg=default]"

echo "${ret}"
